Elastcisearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: Elastics1
    volumes:
      - Esvol:/data/program/
    networks:
      - mynet
       ports:
      - "9200:9200"
Logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: Logstash1
    volumes:
      - Logvol:/data/program/
    networks:
      - mynet
       ports:
      - "5959:5959"
Kibana:
   image: docker.elastic.co/kibana/kibana:6.2.4 
   container_name: Kibana_vol
   volumes:
     - Kibanavol:/data/program/
   networks:
     - mynet
   ports:
     - "5601:5601"
volumes:
   Esvol:
   external: true
   Logvol:
   external: true
   kibanavol:
   external: true
network:
   mynet:
   external: true
